### ISSUE TITLE
push to hackage

### ISSUE THREAD

**Issue by gregwebs** [mpietrzak/yesod-purescript#1]
is this up to date with Yesod 1.4?

Do you want to put it on hackage?

**Comment by jasonzoladz** [comment]
Please push to Hackage as soon as you as can.  Yesod + Purescript is fantastic.

**Comment by paf31** [comment]
:+1: I tried this library out, and it seemed very usable to me. You could always release it as unstable, and  use the PVP to indicate any incompatibility as the API changes.

**Comment by mpietrzak** [comment]
Happy to hear someone likes it, I'll try to put it on Hackage on Friday.

**Comment by sitharus** [comment]
Excellent! I've been using this for my latest project, it's really handy.

**Comment by mpietrzak** [comment]
Published: https://hackage.haskell.org/package/yesod-purescript

**Comment by paf31** [comment]
:cool:
